"""Add composite index for alerts

Revision ID: b4fcc93531b6
Revises: 9546e34ab9c5
Create Date: 2025-02-17 15:06:25.400748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fcc93531b6'
down_revision: Union[str, None] = '9546e34ab9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_subscription_id_is_active', 'alerts', ['subscription_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscription_id_is_active', table_name='alerts')
    # ### end Alembic commands ###
